version: '3'
services:
  squid:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.squid
    container_name: squid
    volumes:
      - /squid_conf/certificado:/scripts
    ports:
      - "Omplir:Omplir"
    networks:
      squid_network:
        ipv4_address: 10.10.1.2
    restart: unless-stopped

  Firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    networks:
     squid_network:
      ipv4_address: 10.10.1.3     
    volumes:
      - "/squid_conf/certificado:/config/downloads:rw"
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
     squid_network:
      ipv4_address: 10.10.1.4
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  radius:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.radius
    container_name: radius
    ports:
      - "Omplir:Omplir"
    networks:
      squid_network:
        ipv4_address: 10.10.1.5
    restart: unless-stopped
    depends_on:
      - db

networks:
  squid_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24


